# Generated by Django 3.2.12 on 2022-04-25 07:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('idMode', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('difficulte', models.CharField(max_length=255)),
                ('tempsImparti', models.IntegerField(default=0)),
                ('pointsNegatifsOn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('idModele', models.AutoField(primary_key=True, serialize=False)),
                ('lien', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('idPartie', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('duree', models.DurationField(default='00:00:00')),
                ('idJoueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popit_app.joueur')),
                ('idMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popit_app.mode')),
                ('idModele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popit_app.modele')),
            ],
        ),
    ]
