# Generated by Django 3.2.12 on 2022-05-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popit_app', '0002_alter_partie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
