# Generated by Django 3.2.12 on 2022-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popit_app', '0003_alter_partie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='pseudo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
